---
auth:
  required: true
  queryParams:
    - name: Parameter name
      value: Parameter value
  headerParams:
    - name: Parameter name
      value: Parameter value
testConfiguration:
  testPaths:
    - testPath: Path 1
      operations:
        - operationId: Operation ID
          method: get
          testParameters:
            - name: Test parameter name
              weight: 0.5
              generators:
              - type: Generator type
                valid: true
                genParameters:
                  - name: Parameter name
                    values:
                      - Parameter value
                  - name: Parameter name 2
                    values:
                      - Parameter value
              - type: Faulty generator type
                valid: false
                genParameters:
                  - name: Parameter name
                    values:
                      - Parameter value
                  - name: Parameter name 2
                    values:
                      - Parameter value
          expectedResponse: Expected HTTP code
